[package]
name = "datafusion-functions-json"
version = "0.1.3"
edition = "2021"
description = "JSON functions for DataFusion"
readme = "README.md"
license = "Apache-2.0"
keywords = ["datafusion", "JSON", "SQL"]
categories = ["database-implementations", "parsing"]
repository = "https://github.com/datafusion-contrib/datafusion-functions-json/"

[dependencies]
arrow = "51"
arrow-schema = "51"
datafusion-common = "38"
datafusion-expr = "38"
datafusion-execution = "38"
jiter = "0.4"
paste = ">=1.0.14"
log = ">=0.4.21"

[dev-dependencies]
datafusion = "38"
tokio = { version = "1.37.0", features = ["full"] }

[lints.clippy]
dbg_macro = "deny"
print_stdout = "deny"

# in general we lint against the pedantic group, but we will whitelist
# certain lints which we don't want to enforce (for now)
pedantic = { level = "deny", priority = -1 }
missing_errors_doc = "allow"
cast_possible_truncation = "allow"


[patch.crates-io]
datafusion = { git = 'https://github.com/apache/datafusion.git', branch = 'main' }
datafusion-common = { git = 'https://github.com/apache/datafusion.git', branch = 'main' }
datafusion-execution = { git = 'https://github.com/apache/datafusion.git', branch = 'main' }
datafusion-expr = { git = 'https://github.com/apache/datafusion.git', branch = 'main' }
