[package]
name = "datafusion-functions-json"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "51.0.0"
arrow-schema = "51.0.0"
datafusion-common = "37.0.0"
datafusion-expr = "37.0.0"
jiter = { git = "https://github.com/pydantic/jiter.git", branch = "next_skip" }
paste = "1.0.14"
log = "0.4.21"
datafusion-execution = "37.0.0"

[dev-dependencies]
datafusion = "37.0.0"
tokio = { version = "1.37.0", features = ["full"] }

[lints.clippy]
dbg_macro = "warn"
print_stdout = "warn"

# in general we lint against the pedantic group, but we will whitelist
# certain lints which we don't want to enforce (for now)
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
cast_possible_truncation = "allow"
